# Generated by Django 6.0.3 on 2026-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
