# Generated by Django 6.0.3 on 2026-03-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAvaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='avarias/')),
                ('descricao', models.CharField(max_length=100)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.servico')),
            ],
        ),
    ]
