# Generated by Django 6.0.3 on 2026-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_servico_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
