# Generated by Django 6.0.3 on 2026-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_servico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
