# Generated by Django 6.0.3 on 2026-03-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_remove_carro_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
