# Generated by Django 6.0.3 on 2026-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0017_alter_servico_status_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status_servico',
            field=models.CharField(default='Na Fila', max_length=100),
        ),
    ]
