# Generated by Django 6.0.3 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_alter_servico_status_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status_servico',
            field=models.CharField(choices=[('Na Fila', 'Na Fila'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status do Serviço'),
        ),
    ]
