# Generated by Django 6.0.3 on 2026-05-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0023_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['-data_entrada', '-id']},
        ),
    ]
