# Generated by Django 6.0.3 on 2026-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0024_alter_servico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Ex: (41) 99999-9999', max_length=15, unique=True),
        ),
    ]
