# Generated by Django 6.0.3 on 2026-03-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_clientes_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
