# Generated by Django 6.0.3 on 2026-03-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_servico_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.carro'),
        ),
    ]
