# Generated by Django 6.0.3 on 2026-03-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_alter_servico_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='placa',
        ),
    ]
