# Generated by Django 6.0.3 on 2026-03-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_alter_carro_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status_servico',
            field=models.CharField(verbose_name=django.db.models.deletion.CASCADE),
        ),
    ]
