# Generated by Django 6.0.3 on 2026-03-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0020_alter_servico_status_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status_servico',
            field=models.CharField(choices=[('NA FILA ', 'Na Fila'), ('EM ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='Na Fila', max_length=20, verbose_name='Status do Serviço'),
        ),
    ]
