# Generated by Django 6.0.3 on 2026-03-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0022_alter_servico_status_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Ex: (41) 99999-9999', max_length=15),
        ),
    ]
