"""
Django settings for AutoCare project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv() # Isso carrega as variáveis do arquivo .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://0357-2804-d55-5e46-6500-3d1d-b0a8-a869-a2.ngrok-free.app']
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AutoCare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AutoCare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================
# CUSTOMIZAÇÃO DO PAINEL ADMIN (JAZZMIN)
# ==========================================

JAZZMIN_SETTINGS = {
    # Textos da aba do navegador e login
    "site_title": "AutoCare Admin",
    "site_header": "AutoCare",
    "site_brand": "AutoCare 🚗",
    "welcome_sign": "Bem-vindo ao Sistema AutoCare",
    "copyright": "AutoCare Gestão Automotiva",

    # Ícones do menu lateral (FontAwesome)
    "icons": {
        "gestao.Cliente": "fas fa-users",
        "gestao.Carro": "fas fa-car",
        "gestao.Servico": "fas fa-tools",
        "gestao.FotoAvaria": "fas fa-camera",
        "auth.Group": "fas fa-users-cog",
        "auth.User": "fas fa-user-shield",
    },

    "order_with_respect_to": [
        "gestao.Cliente",
        "gestao.Carro",
        "gestao.Servico",
        "gestao.FotoAvaria"
    ],

    # Menu lateral com links diretos
    "topmenu_links": [
        {"name": "Início", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Ver Site", "url": "/", "new_window": True},
    ],

    # Atalhos rápidos no menu lateral
    "usermenu_links": [
        {"name": "Suporte", "url": "#", "icon": "fas fa-question-circle"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],  # Esconde auth do menu se quiser deixar mais limpo — remova se precisar
    "hide_models": ["gestao.FotoAvaria"],  # FotoAvaria só aparece como inline no Serviço

    # Botões de ação
    "related_modal_active": True,  # Abre FK em modal ao invés de nova aba

    # Ícone padrão para modelos sem ícone definido
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # Interface
    "changeform_format": "horizontal_tabs",  # abas horizontais no formulário
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # Tema de cores — opções: primary, secondary, info, warning, danger, dark
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",

    # Navbar e sidebar escuros
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,       # Navbar fixa no topo ao rolar

    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,      # Sidebar fixa

    # Cor da sidebar — opções: sidebar-dark-primary, sidebar-dark-danger, sidebar-light-*
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,   # Visual flat/moderno

    # Tema geral — opções: darkly, cyborg, flatly, litera, lumen, minty, pulse, sandstone, simplex, slate, solar, spacelab, superhero, united, yeti
    "theme": "united",
    "dark_mode_theme": "united",

    # Botões
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}